/**********************************************************************
Encrypted Encrypted Media Extensions requirements coverage estimates

This document estimates test coverage on each requirement section in the EME spec.

Coverage data must be manually entered.  

Sample from Media-Source:

var coverage = {
  'widl-MediaSource-activeSourceBuffers': {
    coverage: 50,
    comments: [
      'No real test that the active source buffers are the right ones',
      'No test on the SourceBuffers order'
    ],
    assignee: '@tidoust'
  },
  'widl-AudioTrack-sourceBuffer': 100,
  'widl-VideoTrack-sourceBuffer': 100,
  'widl-TextTrack-sourceBuffer': {
    coverage: 100,
    assignee: '@plehegar'
  }
};

**********************************************************************/

var coverage = {
  'cdm': 100,
  'key-system': 100,
  'key-session': 100,
  'session-id': 100,
  'decryption-key': 100,
  'usable-for-decryption': 100,
  'decryption-key-id': 100,
  'known-key': 100,
  'license': 100,
  'initialization-data': 100,
  'associable-identifiers': 100,
  'permanent-identifier': 100,
  'distinctive-identifier': 100,
  'uses-distinctive-identifiers-or-distinctive-permanent-identifiers': 100,
  'cross-origin': 100,
  'mixed-content': 100,
  'time': 100,
  'widl-Navigator-requestMediaKeySystemAccess-Promise-MediaKeySystemAccess--DOMString-keySystem-sequence-MediaKeySystemConfiguration--supportedConfigurations': 0,
  'get-supported-configuration': 0,
  'get-supported-configuration-and-consent': 0,
  'get-supported-capabilities-for-audio-video-type': 0,
  'are-insecure-contexts-allowed---deprecated': 100,
  'get-consent-status': 0,
  'widl-MediaKeySystemConfiguration-audioCapabilities': 0,
  'widl-MediaKeySystemConfiguration-distinctiveIdentifier': 0,
  'widl-MediaKeySystemConfiguration-initDataTypes': 0,
  'widl-MediaKeySystemConfiguration-label': 0,
  'widl-MediaKeySystemConfiguration-persistentState': 0,
  'widl-MediaKeySystemConfiguration-sessionTypes': 0,
  'widl-MediaKeySystemConfiguration-videoCapabilities': 0,
  'widl-MediaKeySystemMediaCapability-contentType': 0,
  'widl-MediaKeySystemMediaCapability-robustness': 0,
  'widl-MediaKeySystemAccess-keySystem': 0,
  'widl-MediaKeySystemAccess-createMediaKeys-Promise-MediaKeys': 0,
  'widl-MediaKeySystemAccess-getConfiguration-MediaKeySystemConfiguration': 0,
  'widl-MediaKeys-createSession-MediaKeySession-MediaKeySessionType-sessionType': 0,
  'widl-MediaKeys-setServerCertificate-Promise-boolean--BufferSource-serverCertificate': 0,
  'is-persistent-session-type': 0,
  'cdm-unavailable': 0,
  'media-keys-storage': 0,
  'widl-MediaKeySession-closed': 0,
  'widl-MediaKeySession-expiration': 0,
  'widl-MediaKeySession-keyStatuses': 0,
  'widl-MediaKeySession-onkeystatuseschange': 0,
  'widl-MediaKeySession-onmessage': 0,
  'widl-MediaKeySession-sessionId': 0,
  'widl-MediaKeySession-close-Promise-void': 0,
  'widl-MediaKeySession-generateRequest-Promise-void--DOMString-initDataType-BufferSource-initData': 0,
  'widl-MediaKeySession-load-Promise-boolean--DOMString-sessionId': 0,
  'widl-MediaKeySession-remove-Promise-void': 0,
  'widl-MediaKeySession-update-Promise-void--BufferSource-response': 0,
  'widl-MediaKeyStatusMap-size': 0,
  'widl-MediaKeyStatusMap-get-any-BufferSource-keyId': 0,
  'widl-MediaKeyStatusMap-has-boolean-BufferSource-keyId': 0,
  'widl-ctor-MediaKeyMessageEvent--DOMString-type-MediaKeyMessageEventInit-eventInitDict': 0,
  'widl-MediaKeyMessageEvent-message': 0,
  'widl-MediaKeyMessageEvent-messageType': 0,
  'widl-MediaKeyMessageEventInit-message': 0,
  'widl-MediaKeyMessageEventInit-messageType': 0,
  'queue-message': 0,
  'update-key-statuses': 0,
  'update-expiration': 0,
  'session-closed': 0,
  'media-key-session-destroyed': 0,
  'monitor-cdm': 0,
  'exceptions': 0,
  'session-storage': 0,
  'widl-HTMLMediaElement-mediaKeys': 0,
  'widl-HTMLMediaElement-onencrypted': 0,
  'widl-HTMLMediaElement-onwaitingforkey': 0,
  'widl-HTMLMediaElement-setMediaKeys-Promise-void--MediaKeys-mediaKeys': 0,
  'widl-ctor-MediaEncryptedEvent--DOMString-type-MediaEncryptedEventInit-eventInitDict': 0,
  'widl-MediaEncryptedEvent-initData': 0,
  'widl-MediaEncryptedEvent-initDataType': 0,
  'widl-MediaEncryptedEventInit-initData': 0,
  'widl-MediaEncryptedEventInit-initDataType': 0,
  'initdata-encountered': 0,
  'encrypted-block-encountered': 0,
  'attempt-to-decrypt': 0,
  'queue-waitingforkey': 0,
  'resume-playback': 0,
  'media-element-restictions': 100,
  'allow-persistent-data-cleared': 100,
  'limit-or-avoid-use-of-distinctive-identifiers-and-permanent-identifiers': 100,
  'encrypt-identifiers': 100,
  'per-origin-identifiers': 100,
  'allow-identifiers-cleared': 100,
  'support-multiple-keys': 0,
  'licenses-generated-are-independent-of-content-type': 100,
  'support-extraction-from-media-data': 100,
  'unencrypted-container': 100,
  'interoperably-encrypted': 100,
  'unencrypted-in-band-support-content': 100,
  'clear-key-capabilities': 100,
  'clear-key-behavior': 100,
  'clear-key-request-format-example': 0,
  'clear-key-license-format-example': 0,
  'clear-key-release-format-example': 0,
  'clear-key-release-ack-format-example': 0,
  'using-base64url': 100,
  'input-data-security': 100,
  'cdm-security': 100,
  'potential-attacks': 100,
  'security-prompts': 100,
  'potential-attacks-1': 100,
  'mitigations-1': 100,
  'cross-directory-attacks': 100,
  'privacy-disclosure': 100,
  'privacy-fingerprinting': 100,
  'concerns': 100,
  'mitigations-2': 100,
  'like-cookies': 100,
  'privacy-prompts': 100,
  'direct-individualization': 100,
  'app-assisted-individualization': 100,
  'concerns-1': 100,
  'concerns-2': 100,
  'mitigations-5': 100,
  'private-browsing': 100,
  'privacy-secureorigin': 100,
  'null': 100
};